### ISSUE TITLE
微信群的二维码过期啦！

### ISSUE THREAD

**Issue by shaman2009** [tinysou/roadmap#1]
RT

**Comment by yandy** [comment]
谢谢提醒，已经更新 :)

**Comment by shaman2009** [comment]
抱歉， 貌似新的还是显示已过期， 不清楚是什么原因。

On Wed, Oct 8, 2014 at 4:43 PM, Michael Ding notifications@github.com
wrote:

> 谢谢提醒，已经更新 :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tinysou/roadmap/issues/1#issuecomment-58327392.

## 

Best Regards
Fengxiang

**Comment by yandy** [comment]
再试试？似乎腾讯做了限制，一个二维码有邀请人数的上限

**Comment by shaman2009** [comment]
现在OK啦
谢谢

On Wed, Oct 8, 2014 at 5:27 PM, Michael Ding notifications@github.com
wrote:

> 再试试？似乎腾讯做了限制，一个二维码有邀请人数的上限
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tinysou/roadmap/issues/1#issuecomment-58332017.

## 

Best Regards
Fengxiang

**Comment by yandy** [comment]
客气了
